
// This file has been generated by the GUI designer. Do not modify.
namespace PCategoria
{
	public partial class AddAction
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label label;
		private global::Gtk.Entry entry;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Button cancelarButton;
		private global::Gtk.Button aceptarButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PCategoria.AddAction
			this.Name = "PCategoria.AddAction";
			this.Title = global::Mono.Unix.Catalog.GetString ("AddAction");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child PCategoria.AddAction.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label = new global::Gtk.Label ();
			this.label.Name = "label";
			this.label.LabelProp = global::Mono.Unix.Catalog.GetString ("Introduce la categoria a añadir:");
			this.vbox2.Add (this.label);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.entry = new global::Gtk.Entry ();
			this.entry.CanFocus = true;
			this.entry.Name = "entry";
			this.entry.IsEditable = true;
			this.entry.InvisibleChar = '●';
			this.vbox2.Add (this.entry);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.entry]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.cancelarButton = new global::Gtk.Button ();
			this.cancelarButton.CanFocus = true;
			this.cancelarButton.Name = "cancelarButton";
			this.cancelarButton.UseUnderline = true;
			this.cancelarButton.Label = global::Mono.Unix.Catalog.GetString ("Cancelar");
			this.hbox1.Add (this.cancelarButton);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.cancelarButton]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.aceptarButton = new global::Gtk.Button ();
			this.aceptarButton.CanFocus = true;
			this.aceptarButton.Name = "aceptarButton";
			this.aceptarButton.UseUnderline = true;
			this.aceptarButton.Label = global::Mono.Unix.Catalog.GetString ("Aceptar");
			this.hbox1.Add (this.aceptarButton);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.aceptarButton]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 245;
			this.Show ();
		}
	}
}
